apiVersion: v1
kind: Service
metadata:
  name: website-ghost
  labels:
    app: website
    component: ghost
spec:
  type: LoadBalancer
  ports:
  - port: 2368
  selector:
    app: website
    component: ghost
